version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: reiz_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_HOST_PORT}:80"
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis_server
    networks:
      - app-network
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

networks:
  app-network:
    driver: bridge
